"""description of change

Revision ID: 010b8894bbb2
Revises: 9c3b1e46c8a0
Create Date: 2024-09-26 22:55:19.958637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010b8894bbb2'
down_revision: Union[str, None] = '9c3b1e46c8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'banks', ['bank_id'], ['bank_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'bank_id')
    # ### end Alembic commands ###
